- name: Create notebook image build directory
  ansible.builtin.file:
    path: /opt/notebook-build
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
  become: true

- name: Generate notebooks dockerfile
  template:
    src: Dockerfile.j2
    dest: /opt/notebook-build/Dockerfile
    owner: root
    group: root
    mode: 0640
  become: true
  register: notebook_image_dockerfile_generate_result

- name: Build notebooks image
  ansible.builtin.shell: nerdctl build -t "{{ notebook.image_name }}" /opt/notebook-build
  become: true
  when: notebook_image_dockerfile_generate_result.changed
  register: notebook_image_build_result

- name: Output notebook image build
  ansible.builtin.debug:
    var: notebook_image_build_result.stdout
  when: notebook_image_dockerfile_generate_result.changed

- name: Record notebook image changed
  ansible.builtin.set_fact:
    notebook_image_changed: notebook_image_dockerfile_generate_result.changed