- name: Generate Execution Script
  template:
    src: setup_crush_rules.sh
    dest: /opt/setup_crush_rules.sh
    mode: 0700
- name: Run Execution Script
  ansible.builtin.command: /opt/setup_crush_rules.sh
  register: apply_out
- debug: var=apply_out.stdout_lines
- name: Remove Execution Script
  ansible.builtin.file:
    path: /opt/setup_crush_rules.sh
    state: absent