- name: Ensure Tls Certs Directory Exists
  ansible.builtin.file:
    path: /opt/ceph/tls
    mode: '0400'
    state: directory
- name: Copy Server CA Cert
  copy:
    src: "{{ server_ca_cert }}"
    dest: /opt/ceph/tls/ca.crt
    mode: '0400'
- name: Copy Server Cert
  copy:
    src: "{{ server_cert }}"
    dest: /opt/ceph/tls/server.crt
    mode: '0400'
- name: Copy Server Key
  copy:
    src: "{{ server_key }}"
    dest: /opt/ceph/tls/server.key
    mode: '0400'
- name: Ensure Ssh Keys Directory Exists
  ansible.builtin.file:
    path: /opt/ceph/ssh
    mode: '0400'
    state: directory
- name: Copy Public Ssh Key
  copy:
    src: "{{ ssh_key }}"
    dest: /opt/ceph/ssh/ssh_key.pub
    mode: '0400'
- name: Copy Private Ssh Key
  copy:
    src: "{{ ssh_public }}"
    dest: /opt/ceph/ssh/ssh_key
    mode: '0400'