- name: Install pre-requisite libraries
  ansible.builtin.apt:
    pkg:
      - rsync
    update_cache: yes
  become: true

- name: Create llama.cpp Models
  ansible.builtin.file:
    path: "{{ llama_cpp.dest_models_dir | default('/opt/llama.cpp/models') }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
  become: true

- name: Sync models directory
  ansible.posix.synchronize:
    use_ssh_args: true
    src: "{{ llama_cpp.src_models_dir }}/"
    dest: "{{ llama_cpp.dest_models_dir | default('/opt/llama.cpp/models') }}/"