- name: Generate Rgw Pools Setup Script
  template:
    src: setup_rgw_pools.sh.j2
    dest: /opt/setup_rgw_pools.sh
    mode: 0700
  when: has_rgw
- name: Run Rgw Pools Setup Script
  ansible.builtin.command: /opt/setup_rgw_pools.sh
  register: pools_setup_out
  when: has_rgw
- debug: var=pools_setup_out.stdout_lines
  when: has_rgw
- name: Remove Rgw Pools Setup Script
  ansible.builtin.file:
    path: /opt/setup_rgw_pools.sh
    state: absent
  when: has_rgw
- name: Generate Rgw Services Manifest
  template:
    src: rgw_services.yml.j2
    dest: /opt/rgw_services.yml
    mode: 0700
  when: has_rgw
- name: Generate Rgw Service Setup Script
  template:
    src: setup_rgw_service.sh.j2
    dest: /opt/setup_rgw_service.sh
    mode: 0700
  when: has_rgw
- name: Run Rgw Service Setup Script
  ansible.builtin.command: /opt/setup_rgw_service.sh
  register: service_setup_out
  when: has_rgw
- debug: var=service_setup_out.stdout_lines
  when: has_rgw
- name: Remove Rgw Service Setup Script
  ansible.builtin.file:
    path: /opt/setup_rgw_service.sh
    state: absent
  when: has_rgw
- name: Remove Rgw Services Manifest
  ansible.builtin.file:
    path: /opt/rgw_services.yml
    state: absent
  when: has_rgw