- name: Copy Llama.cpp Vulkan Server Script
  ansible.builtin.copy:
    src: llama_cpp_vulkan_server.sh
    dest: /usr/local/bin/llama_cpp_vulkan_server.sh
    mode: 0755
  register: server_script_copy_result
- name: Generate Llama.cpp Vulkan Server Systemd Unit
  template:
    src: llama_cpp_vulkan_server.service.j2
    dest: /etc/systemd/system/llama_cpp_vulkan_server.service
    mode: 0644
  register: server_systemd_unit_template_result
- name: Create Llama.cpp Vulkan Server Config Directory
  ansible.builtin.file:
    path: /etc/llama.cpp/vulkan/server
    mode: '0550'
    state: directory
- name: Create Llama.cpp Vulkan Server Tls Directory
  ansible.builtin.file:
    path: /etc/llama.cpp/vulkan/server/tls
    mode: '0550'
    state: directory
  when: llama_cpp.vulkan.server.tls is defined
- name: Copy Llama.cpp Vulkan Server Cert
  ansible.builtin.copy:
    src: "{{ llama_cpp.vulkan.server.tls.server_cert }}"
    dest: /etc/llama.cpp/vulkan/server/tls/server.crt
    mode: 0640
  register: server_cert_copy_result
  when: llama_cpp.vulkan.server.tls.server_cert is defined
- name: Copy Llama.cpp Vulkan Server Key
  ansible.builtin.copy:
    src: "{{ llama_cpp.vulkan.server.tls.server_key }}"
    dest: /etc/llama.cpp/vulkan/server/tls/server.key
    mode: 0640
  register: server_key_copy_result
  when: llama_cpp.vulkan.server.tls.server_key is defined
- name: Copy Llama.cpp Vulkan Server Ca
  ansible.builtin.copy:
    src: "{{ llama_cpp.vulkan.server.tls.ca_cert }}"
    dest: /etc/llama.cpp/vulkan/server/tls/ca.crt
    mode: 0640
  register: server_ca_copy_result
  when: llama_cpp.vulkan.server.tls.ca_cert is defined
- name: Copy Llama.cpp Vulkan Server Api Keys
  ansible.builtin.copy:
    src: "{{ llama_cpp.vulkan.server.api_keys }}"
    dest: /etc/llama.cpp/vulkan/server/api_keys
    mode: 0640
  register: server_api_keys_copy_result
  when: llama_cpp.vulkan.server.api_keys is defined
- name: Adjust llama.cpp Vulkan service State
  vars:
    service_enabled: "{{ llama_cpp.server.enabled | default(true) | bool }}"
    service_changed: >-
      {{
        (server_script_copy_result.changed | default(false)) or
        (server_systemd_unit_template_result.changed | default(false)) or
        (server_cert_copy_result.changed | default(false)) or
        (server_key_copy_result.changed | default(false)) or
        (server_api_keys_copy_result.changed | default(false))
      }}
  ansible.builtin.systemd:
    name: llama_cpp_vulkan_server.service
    enabled: "{{ service_enabled }}"
    daemon_reload: "{{ server_systemd_unit_template_result.changed | default(false) }}"
    state: "{{ 'stopped' if not service_enabled else ('restarted' if service_changed else 'started') }}"