- name: Setup Amd Gpu Server
  hosts: all
  roles:
    - { role: ../roles/containerd, become: true }
    - { role: ../roles/amd-gpu/rocm/install }
    - role: ../roles/amd-gpu/gpu-power-limit
      become: true
      when: gpu_power_limit is defined
    - role: ../roles/amd-gpu/llama-cpp/models
      when:
       - llama_cpp is defined
       - llama_cpp.src_models_dir is defined
    - role: ../roles/amd-gpu/llama-cpp/bare-metal/install
      become: true
    - role: ../roles/amd-gpu/llama-cpp/bare-metal/server
      become: true
      when: llama_cpp.baremetal.server is defined
  